### ISSUE TITLE
socket connection

### ISSUE THREAD

**Issue by micah** [r3kzi/clamav-prometheus-exporter#6]
We connect to our clamd via sockets, and in order to use your exporter, we'd need to turn on TCP listening. Since an exporter typically runs on the same machine as the thing that it is exporting, it might be a useful change to provide a socket connection capability to speak to clamd as an alternative to the TCP based one.

**Comment by r3kzi** [comment]
Closed via 9f38c205b4a93153261a9e6e223c871b294544e8.

**Comment by micah** [comment]
Excellent, thanks for doing that, and so quickly! I really appreciate it.
